### ISSUE TITLE
Add Seattle Vue.js meetup under "Washington State"

### ISSUE THREAD

**Issue by tessamero** [VueMeetups/vuemeetups.org#108]
Hello, A colleague sent me a link to this overall VueMeetup list as I am looking for Vue events to attend locally. Under "Washington State" i noticed there isn't anything listed, but on the Meetup webpage there is this event: https://www.meetup.com/SeattleVueJS/

I understand not everyone knows about this repo and/or it may be a new group. :) I am just trying to be helpful so more Seattle people can find it.

I have no affiliationwith that meetup group, although I just joined it today.  Thank you!

**Comment by tessamero** [comment]
Hi @bencodezen , as you already know, I decided to take over the Vue Seattle group and make it active : https://www.meetup.com/SeattleVueJS

Does this mean I get to be listed now? :)

**Comment by bencodezen** [comment]
@tessamero Of course! Do you want me to make the code change or would you like the PR credit? Also, the new repo is here: https://github.com/vuejs/events

It was great meeting you and let me know if you have any questions in the meantime!

**Comment by bencodezen** [comment]
https://github.com/vuejs/events/issues/26
