### ISSUE TITLE
New Meetup: Corridor Vue Developers

### ISSUE THREAD

**Issue by jbrunken** [VueMeetups/vuemeetups.org#115]
Starting a new meetup for developers in the Cedar Rapids/Iowa City Iowa area.

https://www.meetup.com/Corridor-Vue-Developers/

I've spoken briefly with @bencodezen about this on Discord.

**Comment by bencodezen** [comment]
@jbrunken Thanks for opening an issue! It's now in the repo:

https://github.com/vuejs/events/tree/master/src/meetups#united-states

Let me know if you need anything else in the meantime!
