### ISSUE TITLE
Vue Costa Rica

### ISSUE THREAD

**Issue by kevinrodriguez-io** [VueMeetups/vuemeetups.org#117]
Hi guys, we're hosting a vue meetup group in Costa Rica :)
https://www.meetup.com/Vue-Costa-Rica/

**Comment by bencodezen** [comment]
Hi @kevinrodriguez-io! Just wanted to let you know that we have moved to and will update the info over there. Thank you for opening an issue!

**Comment by bencodezen** [comment]
https://github.com/vuejs/events/issues/23
