### ISSUE TITLE
Please add me to your list - VueJS Manchester Community (UK)

### ISSUE THREAD

**Issue by Emanuell-Dan-Minciu** [VueMeetups/vuemeetups.org#12]
Hello,

My name is Emanuell and I am the organiser of Vue.JS meetup events in the North West region of the UK. Could you please add us to your list?

Here we are: https://www.meetup.com/VueJS-Manchester/

Kind regards,
Emanuell

**Comment by bencodezen** [comment]
@Emanuell-Dan-Minciu Done! Thanks for submitting an issue!
