### ISSUE TITLE
Vue meet-up in Cleveland

### ISSUE THREAD

**Issue by BenRunInBay** [VueMeetups/vuemeetups.org#37]
Vue is great and I'm thrilled to be doing a demo/overview of it for the Cleveland tech community:
https://www.meetup.com/Cleveland-VueJS/events/253812868/

**Comment by bencodezen** [comment]
That's awesome man! We'll make sure to tweet and share the event!

**Comment by bencodezen** [comment]
@BenRunInBay Hope that your event went well! Looking forward to seeing more events from Cleveland!
