### ISSUE TITLE
Vue.js LA Meetup page

### ISSUE THREAD

**Issue by kobione** [VueMeetups/vuemeetups.org#39]
Hello,

This is a great list.  Thank you for your work.

We updated the Vue.js LA Meetup page.  I wanted to update the url.  The new url is https://www.meetup.com/VuejsLA/ (you will see that your old url redirect to there, for now).  

Thank you.
Kobi (VuejsLA organizer)

**Comment by bencodezen** [comment]
All done @kobione! Thanks for letting us know of the update!

**Comment by kobione** [comment]
Thanks Ben!
  

  
  

  
  
>
