### ISSUE TITLE
Proposal to centralize all conference related info and resources

### ISSUE THREAD

**Issue by bencodezen** [VueMeetups/vuemeetups.org#4]
Since Vue already has 3 official conferences under its belt, I thought it could be useful for users to have a centralized location in the docs to see all the Vue.js conferences that have occurred / will happen along with easy to reference links to the various resources for those conferences.

Does anyone else think this is valuable? And if so, should we keep it within this "Community" page or is it worth creating a sister page to the "Community" effort for this?

**Comment by atrunelle** [comment]
I think it'll be really useful. I see there is an Event page with a big list of Events. It could be improved to filter Events depending on their type, as well as showing types in the list to quickly scan through. I find this big list quite hard to read at the moment.
