### ISSUE TITLE
大陆地区需要个聚会

### ISSUE THREAD

**Issue by Jet12138** [VueMeetups/vuemeetups.org#50]
郑州在此。Zhen Zhou

**Comment by Jet12138** [comment]
怎么开，我能力有限。只能开10几个人的聚会

**Comment by bencodezen** [comment]
@Jet12138 那就够了！只要有人要一起谈Vue.js的话题。

开法很容易。只要你有一个网页告诉人家活动的地方，时间，和话题，就可以了！

你住在哪个城市？

**Comment by bencodezen** [comment]
@Jet12138 你好！最近没有收到你的答案，所以我暂时把这个issue解决。如果你还有问题，我希望你会再开这个issue或开一个新的issue。新年快乐！
