### ISSUE TITLE
Add Vue Vixens events

### ISSUE THREAD

**Issue by bencodezen** [VueMeetups/vuemeetups.org#57]
https://vuevixens.org/

**Comment by gustojs** [comment]
All of them or the ones happening outside of Vue conferences or roadtrips (as it would be doubling the events)?

**Comment by atrunelle** [comment]
I think we should add a type of `workshop` for those. Might even be useful to be able to filter the VueVixens events from others as well.

It'll be nice if we could fetch those dynamically. They seem to use storyblok from what I can see. Maybe we should check with Natalia if we could fetch the API for the workshops

**Comment by NataliaTepluhina** [comment]
@atrunelle we can do it definitely ;)

In fact you will need to make 1 API call to fetch the whole list of events and every item will have an `internal URL` (relative to vuevixens,org). I can share the token with you so you will be authorized to perform this call ;)

**Comment by bencodezen** [comment]
@atrunelle Do you want to close this with your PR? Or do you want to keep this open until we get the regularly scheduled script to run?

**Comment by atrunelle** [comment]
@bencodezen I think the scope of the scheduling is greater than this tickets. This is technically done as we now see the events on the website. I would treat it as another ticket and close this one

**Comment by bencodezen** [comment]
@atrunelle Agreed! Closing now.

**Comment by bencodezen** [comment]
For future reference, the PR that closed this ticket is https://github.com/VueMeetups/vuemeetups.org/pull/65
