### ISSUE TITLE
Starting a new meetup

### ISSUE THREAD

**Issue by simplytammy** [VueMeetups/vuemeetups.org#62]
I am a newbie to Vue and I just realised that there isn't any Vue meetup around my region (Nigeria) and I would like to start one.

**Comment by bencodezen** [comment]
Hi @ogb-tammy. Thanks for reaching out! Have you tried getting in touch with the Vue.js Nigeria group on Twitter? This is one of the main efforts I've seen, but am unaware if they have hosted any events.

https://twitter.com/VuejsNigeria

**Comment by ogb-tammy** [comment]
I tried reaching out, but I got no feedbacks.
I would really like to start a new meetup at my University and get more people to learn and work with Vue. Although I'm new to Vue, talking about Vue to other people would help me grow as well as spread the word.

**Comment by bencodezen** [comment]
@ogb-tammy In that case, we would love to have you start a group that is specific to your city! Based on a little research, it seems like it could be something like VueChoba or VuejsChoba? Feel free to correct me if I used the wrong city.

As far as next steps, do you plan on using a service like Meetup.com? If not, you can use a service like Eventbrite to host free events at no cost. Facebook Groups are another way to organize your group as well. 

Once you have your group site setup and have your first meetup scheduled, we'd be more than happy to help let people know about it!

Let me know if you have any other questions!

**Comment by ogb-tammy** [comment]
Alright..
Thank you very much.
I'll definitely get back to you with more details

**Comment by susthitsoft** [comment]
@bencodezen How do I get a Meetup started in Pune, INDIA?

**Comment by bencodezen** [comment]
Hey @susthitsoft! As far as starting a new meetup, I've written a guide here: https://www.vuemeetups.org/resources/#introduction

Once you've established your meetup, feel free to submit a PR or issue to update the site and we are happy to help retweet about your events and such.

Let me know if you have any questions!
