### ISSUE TITLE
Ability for server to run script automatically to fetch events

### ISSUE THREAD

**Issue by bencodezen** [VueMeetups/vuemeetups.org#66]
See https://github.com/VueMeetups/vuemeetups.org/pull/65 for discussion, but basically we need to have the server run the script regularly to fetch events. More details to come later.

**Comment by atrunelle** [comment]
@bencodezen I updated the netlify config. It now runs the generate script before deploy. Just need to add the zappier config to schedule deploys

**Comment by bencodezen** [comment]
@atrunelle I will take care of this this week!

**Comment by bencodezen** [comment]
@atrunelle It's all done! Got the Zap turned on. Let me know if it is ever acting up, but excited this is finally working. Thanks for all your help on this!
