### ISSUE TITLE
Proposal: Reverse the order of past meetups

### ISSUE THREAD

**Issue by gustojs** [VueMeetups/vuemeetups.org#76]
While it's good that the upcoming meetups are being displayed chronologically, in case of past meetups it means that what we see first are meetups from half of a year ago.

It could be nice to revert that order and show the meetups that just ended first, just like it was previously before that page was dynamic.

What do you think about it?

**Comment by bencodezen** [comment]
That's a great point! 

What are your thoughts @atrunelle?

**Comment by atrunelle** [comment]
Sounds good, especially if that's how it was done before. I can have a look next week, it should be easy to do
