### ISSUE TITLE
Singapore VueJS Meetup Group

### ISSUE THREAD

**Issue by aelbore** [VueMeetups/vuemeetups.org#82]
Here's the Singapore VueJS Meetup Group, Can you add this?
https://www.meetup.com/Vue-JS-Singapore

**Comment by bencodezen** [comment]
Hi @aelbore! You can find the meetup at https://www.vuemeetups.org/find/#singapore

**Comment by aelbore** [comment]
@bencodezen thanks i didn't notice it. many thanks. :)

**Comment by bencodezen** [comment]
You're welcome @aelbore! Glad to have you here!
