### ISSUE TITLE
Vuejs kenya

### ISSUE THREAD

**Issue by stannlee** [VueMeetups/vuemeetups.org#84]
We have a large community of vuejs users in kenya and I think it's appropriate for us to have a community

**Comment by stannlee** [comment]
Hello @bencodezen I just did but I think I need more time to internalize it

**Comment by bencodezen** [comment]
No problem. I'm happy to help you as you work through it. Looking forward to seeing a Vue community grow in Kenya!

**Comment by bencodezen** [comment]
@stannlee I'll be closing this for now, but please to re-open or create a new issue whenever you're ready / have questions!

**Comment by stannlee** [comment]
Ok sir
