### ISSUE TITLE
Start Vue.js meetup in my University.

### ISSUE THREAD

**Issue by simplytammy** [VueMeetups/vuemeetups.org#89]
I'd like to get the greenlight to start a vuejs community specific to my university. I've tried to put to put together a couple of people for a community specific to my city, but that has not been successful. Getting one up and running in my university has prospects of starting in 2019 and I would like to know inform you of this plan

**Comment by bencodezen** [comment]
@simplytammy Sounds good! Feel free to reach out with the group info or let me know if you  have any questions!

**Comment by simplytammy** [comment]
Alright! Thanks alot

**Comment by bencodezen** [comment]
@simplytammy The purpose of creating a local community is to create a reliable place for people to go to not only get help, but to share knowledge and sometimes to even just have a friend to bounce ideas off when writing code.

More importantly, it provides a safe place where people who are new to the framework know that they can go to learn more about Vue.js without trying to figure it out on their own.

In addition, another upside of having a local Vue.js community group is that this gives people the opportunity to practice speaking and sharing knowledge with the community. 

And it just occurred to me, but please feel free to create your Vue.js group based on the city. No need to create it specifically to your university. That way you will have the opportunity to grow it larger if there is interest.

Let me know if you have additional questions!

**Comment by simplytammy** [comment]
Alright.. Thank you very much
