### ISSUE TITLE
Vue.is meet up Nigeria

### ISSUE THREAD

**Issue by paulokoduwa** [VueMeetups/vuemeetups.org#90]
Looking forward to organising vue is meet up in Nigeria

**Comment by bencodezen** [comment]
Hello @paulokoduwa! There is an initiative for one in Nigeria here https://twitter.com/VuejsNigeria and https://www.facebook.com/vuejsNG/, but I have not seen any official events.

What I would recommend is starting a Vue.js meetup in your city similar to how the United States has lots of smaller meetup groups. within different states.

How does that sound?

**Comment by paulokoduwa** [comment]
That will be awesome, I don't live in the capital Lagos, I am sure I can
start one in Benin city where I live.
Do you give any support like T-shirts for events

**Comment by bencodezen** [comment]
@paulokoduwa Sounds great. Be sure to submit a PR or issue when you've created your group's page along with the meetup info so we can help spread the word!

**Comment by paulokoduwa** [comment]
Sure I will,  am looking forward to learning more and spreading VUEJS

**Comment by bencodezen** [comment]
@paulokoduwa I'm going to close this issue for now, but please feel free to re-open it or open a new issue if you have any questions!
