### ISSUE TITLE
VueJS Lyon (France)

### ISSUE THREAD

**Issue by nicooprat** [VueMeetups/vuemeetups.org#93]
Hi there,

One more to the list!

https://www.meetup.com/fr-FR/Vue-js-Lyon/

Thanks.

**Comment by bencodezen** [comment]
@nicooprat Awesome! Just added it in and it should deploy shortly. Thanks for creating an issue!

**Comment by nicooprat** [comment]
Thanks for your reactivity!

--
Nico Prat
nicooprat@gmail.com
@nicooprat
